default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: sample-app_development
test:
  <<: *default
  database: sample-app_test
production:
  <<: *default
  database: sample-app_production
  username: sample-app
  password: <%= ENV['SAMPLE-APP_DATABASE_PASSWORD'] %>

